FROM node:8.15-alpine

MAINTAINER Bruno A. Caceres <brunoacaceres@gmail.com>

WORKDIR /opt/bigboxx/api

RUN apk add --no-cache --virtual .build-deps git 
RUN git clone https://github.com/e-cattle/api . 
RUN npm install 

EXPOSE 3001

CMD [ "npm", "start" ]