FROM node:8.15-alpine

MAINTAINER Bruno A. Caceres <brunoacaceres@gmail.com>

WORKDIR /opt/bigboxx/kernel

RUN apk add --no-cache --virtual .build-deps git 
RUN git clone https://github.com/e-cattle/kernel . -b dev
RUN npm install 

EXPOSE 3000

CMD [ "npm", "start" ]