version: '3'

services:
  bigboxx-mongo:
    image: mongo:3
    container_name: bigboxx-mongo
    hostname: bigboxx-mongo
    ports: 
      - "27017:27017"
    environment:
      - TZ=America/Campo_Grande

  bigboxx-kernel:
    build: 
      context: .
      dockerfile: Dockerfile-kernel
    image: bigboxx/kernel
    container_name: bigboxx-kernel
    hostname: bigboxx-kernel
    ports: 
      - "3000:3000"
    environment:
      - TZ=America/Campo_Grande
      - NODE_ENV=docker

  bigboxx-api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    image: bigboxx/api
    container_name: bigboxx-api
    hostname: bigboxx-api
    ports: 
      - "3001:3001"
    environment:
      - TZ=America/Campo_Grande
      - NODE_ENV=docker